name: Storybook

on:
  push:
    branches: master

env:
  CF_API: https://api.eu-de.cf.cloud.ibm.com
  CF_ORG: europeana-dev
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_SPACE: test
  CF_USERNAME: apikey

jobs:
  update:
    name: Update Storybook on Cloud Foundry (CF)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      id: cache-node
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
    - if: steps.cache-node.outputs.cache-hit != 'true'
      run: npm install
    # TODO: build and push a Docker image for this to speed it up?
    - name: Install CF CLI & plugins
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get -q update && sudo apt-get -yq install cf7-cli
        cf --version
    - run: npm run build-storybook
    - name: Login to CF
      run: cf login -a ${CF_API} -u ${CF_USERNAME} -p "${CF_PASSWORD}" -o ${CF_ORG} -s ${CF_SPACE}
    - name: Deploy to CF
      run: cd storybook-static && cf push portaljs-storybook -f ../deploy/cloud-foundry/storybook.manifest.yml
